#include <iostream>
#include <windows.h>
using namespace std;
void printmaze();
void printplayer(int x,int y);
void gotoxy(int x,int y);
main()
{
 system("cls");
 printmaze();
 gotoxy(4,5);
 cout << "P";
 gotoxy(0,20);
 while(true)
{
 int x;
 gotoxy(4,5);
 printplayer(x,5);
 x=x+1;
 if (x==44)
 {
  x=43;
  x=42;
  x=41;
  x=40;
  x=4;
}
}
}
void printmaze()
{
 cout << "##############################################" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "#                                            #" <<endl;
 cout << "##############################################" <<endl;
}
void gotoxy(int x,int y)
{
COORD coordinates;
coordinates.X=x;
coordinates.Y=y;
SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE),coordinates);
}
void printplayer(int x,int y)
{
 gotoxy(4,5);
 cout << "P";
 Sleep(500);
 gotoxy(4,5);
 cout << " ";
 gotoxy(5,5);
 cout << "P";
 Sleep(500);
 gotoxy(5,5);
 cout << " ";
 gotoxy(6,5);
 cout << "P";
 Sleep(500);
 gotoxy(6,5);
 cout << " ";
  gotoxy(7,5);
 cout << "P";
 Sleep(500);
 gotoxy(7,5);
 cout << " ";
 gotoxy(8,5);
 cout << "P";
 Sleep(500);
 gotoxy(8,5);
 cout << " ";
 gotoxy(9,5);
 cout << "P";
 Sleep(500);
 gotoxy(9,5);
 cout << " ";
 gotoxy(10,5);
 cout << "P";
 Sleep(500);
 gotoxy(10,5);
 cout << " ";
 gotoxy(11,5);
 cout << "P";
 Sleep(500);
 gotoxy(11,5);
 cout << " ";
 gotoxy(12,5);
 cout << "P";
 Sleep(500);
 gotoxy(12,5);
 cout << " ";
 gotoxy(12,5);
 cout << "P";
 Sleep(500);
 gotoxy(12,5);
 cout << " ";
 gotoxy(13,5);
 cout << "P";
 Sleep(500);
 gotoxy(13,5);
 cout << " ";
 gotoxy(14,5);
 cout << "P";
 Sleep(500);
 gotoxy(14,5);
 cout << " ";
 gotoxy(15,5);
 cout << "P";
 Sleep(500);
 gotoxy(15,5);
 cout << " ";
 gotoxy(16,5);
 cout << "P";
 Sleep(500);
 gotoxy(16,5);
 cout << " ";
 gotoxy(17,5);
 cout << "P";
 Sleep(500);
 gotoxy(17,5);
 cout << " ";
 gotoxy(18,5);
 cout << "P";
 Sleep(500);
 gotoxy(18,5);
 cout << " ";
 gotoxy(19,5);
 cout << "P";
 Sleep(500);
 gotoxy(19,5);
 cout << " ";
 gotoxy(20,5);
 cout << "P";
 Sleep(500);
 gotoxy(20,5);
 cout << " ";
 gotoxy(21,5);
 cout << "P";
 Sleep(500);
 gotoxy(21,5);
 cout << " ";

 gotoxy(22,5);
 cout << "P";
 Sleep(500);
 gotoxy(22,5);
 cout << " ";
 gotoxy(23,5);
 cout << "P";
 Sleep(500);
 gotoxy(23,5);
 cout << " ";
 gotoxy(24,5);
 cout << "P";
 Sleep(500);
 gotoxy(24,5);
 cout << " ";
 gotoxy(25,5);
 cout << "P";
 Sleep(500);
 gotoxy(25,5);
 cout << " ";
 gotoxy(26,5);
 cout << "P";
 Sleep(500);
 gotoxy(26,5);
 cout << " ";
 gotoxy(27,5);
 cout << "P";
 Sleep(500);
 gotoxy(27,5);
 cout << " ";
 gotoxy(28,5);
 cout << "P";
 Sleep(500);
 gotoxy(28,5);
 cout << " ";
 gotoxy(29,5);
 cout << "P";
 Sleep(500);
 gotoxy(29,5);
 cout << " ";
 gotoxy(30,5);
 cout << "P";
 Sleep(500);
 gotoxy(30,5);
 cout << " ";
 gotoxy(31,5);
 cout << "P";
 Sleep(500);
 gotoxy(31,5);
 cout << " ";
 gotoxy(32,5);
 cout << "P";
 Sleep(500);
 gotoxy(32,5);
 cout << " ";
 gotoxy(33,5);
 cout << "P";
 Sleep(500);
 gotoxy(33,5);
 cout << " ";
 gotoxy(34,5);
 cout << "P";
 Sleep(500);
 gotoxy(34,5);
 cout << " ";
 gotoxy(35,5);
 cout << "P";
 Sleep(500);
 gotoxy(35,5);
 cout << " ";
 gotoxy(36,5);
 cout << "P";
 Sleep(500);
 gotoxy(36,5);
 cout << " ";
 gotoxy(37,5);
 cout << "P";
 Sleep(500);
 gotoxy(37,5);
 cout << " ";
 gotoxy(38,5);
 cout << "P";
 Sleep(500);
 gotoxy(38,5);
 cout << " ";
 gotoxy(39,5);
 cout << "P";
 Sleep(500);
 gotoxy(39,5);
 cout << " ";
 gotoxy(40,5);
 cout << "P";
 Sleep(500);
 gotoxy(40,5);
 cout << " ";
 gotoxy(41,5);
 cout << "P";
 Sleep(500);
 gotoxy(41,5);
 cout << " ";
 gotoxy(42,5);
 cout << "P";
 Sleep(500);
 gotoxy(42,5);
 cout << " ";
 gotoxy(43,5);
 cout << "P";
 Sleep(500);
 gotoxy(43,5);
 cout << " ";
 gotoxy(44,5);
 cout << "P";
 Sleep(500);
 gotoxy(44,5);
 cout << " ";
  gotoxy(0,20);
}
